[package]
name = "Engima"
version = "0.1.1"
edition = "2021"
default-run = "enigma"
license = "MIT"
license-file = "LICENSE"
description = "A simple Enigma machine simulator"
repository = "https://github.com/Andrew-McCall/Engima-rs"
readme = "README.md"
authors = ["Andrew McCall"]
documentation = "https://github.com/Andrew-McCall/Engima-rs#readme"
keywords = [
    "enigma",
    "enigma-machine",
    "enigma-simulator",
    "enigma-simulation",
    "enigma-sim",
    "enigma-simulator-rs",
    "enigma-machine-rs",
    "enigma-simulation-rs",
    "enigma-sim-rs",
    "enigma-simulator-rust",
    "enigma-machine-rust",
    "enigma-simulation-rust",
    "enigma-sim-rust",
    "enigma-rs",
    "enigma-rust",
    "enigma-machine-simulator",
    "enigma-machine-simulation",
    "enigma-machine-sim",
    "enigma-machine-simulator-rs",
    "enigma-machine-simulation-rs",
    "enigma-machine-sim-rs",
    "enigma-machine-simulator-rust",
    "enigma-machine-simulation-rust",
    "enigma-machine-sim-rust",
    "cli",
]
categories = [
    "cryptography",
    "enigma",
    "enigma-machine",
    "enigma-simulator",
    "enigma-simulation",
    "enigma-sim",
    "enigma-simulator-rs",
    "enigma-machine-rs",
    "enigma-simulation-rs",
    "enigma-sim-rs",
    "enigma-simulator-rust",
    "enigma-machine-rust",
    "enigma-simulation-rust",
    "enigma-sim-rust",
    "enigma-rs",
    "enigma-rust",
    "enigma-machine-simulator",
    "enigma-machine-simulation",
    "enigma-machine-sim",
    "enigma-machine-simulator-rs",
    "enigma-machine-simulation-rs",
    "enigma-machine-sim-rs",
    "enigma-machine-simulator-rust",
    "enigma-machine-simulation-rust",
    "enigma-machine-sim-rust",
]

[dependencies]


[[bin]]
name = "enigma"
path = "src/enigma/main.rs"

[[bin]]
name = "enigma-rs"
path = "src/enigma-rs/main.rs"
