[package]
name = "Engima"
version = "0.1.1"
edition = "2021"
default-run = "enigma"
license = "MIT"
license-file = "LICENSE"
description = "A simple Enigma machine simulator"
repository = "https://github.com/Andrew-McCall/Engima-rs"
readme = "README.md"
authors = ["Andrew McCall"]
documentation = "https://github.com/Andrew-McCall/Engima-rs#readme"
keywords = ["enigma", "machine", "simulator", "enigma-machine", "cryptography"]
categories = [
    "cryptography",
    "simulator",
    "enigma",
    "machine",
    "encryption",
    "decryption",
]

[dependencies]


[[bin]]
name = "enigma"
path = "src/enigma/main.rs"

[[bin]]
name = "enigma-rs"
path = "src/enigma-rs/main.rs"
