[package]
name = "Engima"
version = "0.1.1"
edition = "2021"
default-run = "enigma"

[dependencies]


[[bin]]
name = "enigma"
path = "src/enigma/main.rs"

[[bin]]
name = "enigma-rs"
path = "src/enigma-rs/main.rs"
