[package]
name = "Engima"
version = "0.1.1"
edition = "2021"
default-run = "enigma-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "enigma"
path = "src/enigma/main.rs"

[[bin]]
name = "enigma-rs"
path = "src/enigma-rs/main.rs"
